{% set name = "eigenpy" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00848b0ccb52533a7b2cdc36d3f8caf2276e274bbbcce6577f5fb014ac1dd9af

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - boost
    - numpy
    - python
  run:
    - eigen
    - boost
    - {{ pin_compatible('numpy') }}
    - python

test:
  requires:
    - pkg-config
    - boost
  imports:
    - eigenpy
  commands:
    - pkg-config --modversion eigenpy

about:
  home: http://github.com/stack-of-tasks/eigenpy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bindings between Numpy and Eigen using Boost.Python
  dev_url: https://github.com/stack-of-tasks/eigenpy

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - seanyen
