travis:
  secure:
    BINSTAR_TOKEN: vvnJLCCtvTmF3O3201SbmJAW+o+N9gHjJAN8O0TJtv25XgDaM57clalvKuaYJIVckzz2Imt3ssLS+3Zhg/yLcFdJOaQ0LeM4kJ1BhD52ez2O5W4mDsrO7vM4CvTMbw8gGoJy4KmXfu4307Uh3iHSdkSjpWsFViiYADChd3Og4KqJ9zatPgFLrrhzlcAyoQJ4iKqDyAbrvy5ipb9qt8AgS4kLGzdC+PpdbDN3i97nhz6KDPY6lT1ydPYbOOnmsOuLU/wklaf9u/u/8TntuosYZiN1Oi+mpXy7CPwwboi08E2ZhJEN8eLCGVXyQlM4E7scvKfrGQbbdHu3yP2BRltZyxBE3OrDeWRP5u6RXucFe0EkkvrSR/2pSrejcNG3ADAtHU9nO6dhFdyKsFk3jP9iWvv7jEK6cuF2fpkrV9+Bpft/ZW5hn5AR9XNEVIyRHKdGwJILDnOZ9KC+Siaq5J6MNDpLSEpVHKSCL3xAeL4v0MRQ77xRwY+USNdm3TJaYgePDysq/tY99IophRK6JM9YNMebF8Tvl/CytM4zQQKimw3m1tYDtefRm5f27fLFJW2kW2txVkBZaarAFcJXqm2Ip3h7rx5RdH7ZaDVgPYq7Aex77gU2nKd0QyPW9+p7sb3k8+EsAtonkIDBKHYoV1tFYsBkradHXkviqM2yQ4s1wcQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
